blank_issues_enabled: false
contact_links:
  - name: Direct Licensing Email Support
    url: mailto:harshitpd1729@://gmail.com
    about: Reach out directly via email if you prefer not to use a public GitHub ticket.
