#ifndef QMC_SPIN_CHAIN_H
#define QMC_SPIN_CHAIN_H

#include "../core/complex.h"
#include "../core/sparse.h"
#include "../core/vector.h"
#include <stdint.h>

/*
 * Translation-symmetry-adapted exact diagonalization for the spin-1/2 XXZ
 * chain on a periodic ring, plus Lanczos continued-fraction evaluation of
 * the dynamical structure factor S^{zz}(q, omega).
 *
 * H = \sum_j [ Jz S^z_j S^z_{j+1} + (Jxy/2)(S^+_j S^-_{j+1} + S^-_j S^+_{j+1}) ]
 *
 * Convention: site states are packed into the bits of a uint64_t (bit j = 0
 * -> spin up, S^z_j = +1/2; bit j = 1 -> spin down, S^z_j = -1/2). This
 * limits N <= 63, far beyond what dense/sparse storage can handle anyway.
 *
 * Only two symmetries are exploited here: total S^z (fixed by choosing the
 * number of up spins, nup) and translation (fixed by choosing a momentum
 * index k in units of 2*pi/N). Point-group parity / spin-inversion are NOT
 * implemented -- see the module's implementation notes for why folding
 * those in is subtler than a simple sign flip and has been deliberately
 * left for a follow-up.
 */

typedef struct {
  int N;         /* number of sites */
  int nup;       /* number of up spins (fixes the S^z sector) */
  int k;         /* momentum index, 0 <= k < N, in units of 2*pi/N */
  int dim;       /* number of symmetry-adapted basis states in this sector */
  uint64_t *rep; /* size dim, sorted ascending: representative bitstrings */
  int *period;   /* size dim: R_a, the translation period of rep[a] */
} spin_sector_t;

/* Build the (nup, k) symmetry sector for an N-site ring. Enumerates all
 * C(N,nup) basis states, keeps only translation representatives (the
 * lexicographically/numerically smallest bitstring in each translation
 * orbit) whose period R_a is compatible with k (i.e. k*R_a = 0 mod N, the
 * condition for a nonzero-norm momentum eigenstate to exist on that orbit).
 *
 * Returns NULL on invalid input (N<=0, N>63, nup<0, nup>N, k<0, k>=N) or
 * allocation failure. Free with spin_sector_free.
 */
spin_sector_t *spin_sector_build(int N, int nup, int k);
void spin_sector_free(spin_sector_t *sec);

/* Binary search for a representative bitstring in a sector's sorted rep[]
 * array. Returns its index, or -1 if not present in this sector. */
int spin_sector_find(const spin_sector_t *sec, uint64_t rep);

/* Build the matrix-free XXZ Hamiltonian restricted to one symmetry sector,
 * returned in CSR form (reusing core/sparse.h so it plugs directly into
 * lanczos_eigs / lanczos_tridiagonalize). pbc selects periodic (ring) vs
 * open boundary conditions for the j -> j+1 bonds.
 *
 * Construction is a two-pass, row-parallel (OpenMP) build: pass 1 counts
 * nonzeros per representative row independently in parallel and prefix-sums
 * them into row_ptr; pass 2 fills each row's disjoint slice of col_ind/
 * values in parallel. Because each row's output slice is known in advance
 * and never touched by another thread, this needs no locks, no atomics, and
 * no thread-private scratch buffers to reduce afterward.
 */
sparse_matrix_t *spin_sector_hamiltonian(const spin_sector_t *sec, double Jxy,
                                         double Jz, int pbc);

/* Apply S^z_q = (1 / \sqrt(N)) * \\sum_j  * \exp(i*q*j) S^z_j to a state given by its
 * coefficients (psi0, length src->dim) in the src sector's symmetry-adapted
 * basis, where q = 2*pi*q_index/N.
 *
 * S^z_j is diagonal in the computational (S^z eigenbasis) basis, so this
 * operator maps src's momentum k to k_target = (src->k + q_index) mod N
 * while leaving nup (and hence the S^z sector) fixed. The output is
 * returned unnormalized, together with its squared norm I0 = <phi0|phi0>,
 * which is itself the q-resolved total spectral weight (the equal-time
 * structure factor at momentum q).
 *
 * *out_target receives a newly built target sector (caller frees it).
 * *out_phi0 receives the unnormalized excitation vector in that sector's
 * basis (caller frees it). *out_I0 receives its squared norm.
 *
 * Returns 0 on success, nonzero on invalid input or allocation failure (in
 * which case no sector/vector is allocated).
 */
int spin_apply_szq(const spin_sector_t *src, const cvector_t *psi0, int q_index,
                   spin_sector_t **out_target, cvector_t **out_phi0,
                   double *out_I0);

/* Evaluate the Lanczos continued-fraction dynamical structure factor
 *   S(q, omega) = -(1/pi) * Im[ I0 * <f0| (E0 + omega + i*eta - H)^{-1} |f0> ]
 * from tridiagonal coefficients (alpha, beta) already generated by
 * lanczos_tridiagonalize on the *normalized* excitation vector f0 =
 * phi0/ \sqrt(I0), plus the separately-stored I0 and ground-state energy E0.
 *
 * eta > 0 is the Lorentzian broadening (finite-size chains have delta-
 * function poles on the real axis; eta smooths them into a spectrum you can
 * plot on a finite frequency mesh).
 */
double spin_dsf_continued_fraction(const double *alpha, const double *beta,
                                   int m, double E0, double I0, double omega,
                                   double eta);

#endif
