#ifndef QMC_VARIATIONAL_H
#define QMC_VARIATIONAL_H

#include "../core/vector.h"
#include "potentials.h"
#include "wavefn.h"

/* Compute expectation value of Hamiltonian for trial wavefunction */
double variational_energy(const wavefunction_t *wf, potential_fn V,
                          void *params);

/* Minimize energy with respect to single parameter alpha.
   The trial wavefunction is generated by function that takes alpha and fills wf.
   HACK: perform simple grid search or golden section search.
*/
double variational_minimize(double alpha_min, double alpha_max,
                            void (*trial_func)(double alpha,
                                               wavefunction_t *wf),
                            wavefunction_t *wf, potential_fn V, void *params,
                            double tol);

#endif
