[book]
title = "QMC : Quantum Mechanics implementations in C"
authors = ["Harshit Dhanwalkar"]
description = "Quantum Mechanics implementations in C."
language = "en"
src = "src"

[preprocessor.katex]

[output.html]
smart-punctuation = true
definition-lists = true
admonitions = true
mathjax-support = false
git-repository-url = "https://github.com/Harshit-Dhanwalkar/QMC"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/Harshit-Dhanwalkar/QMC/edit/main/docs/src/{path}"
# additional-css = ["custom.css"]
# default-theme = "navy"
# preferred-dark-theme = "navy"

[output.linkcheck]
follow-web-links = false

[output.html.search]
enable = true

# [output.wordcount]
# optional = true
